AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation workshop - parameters (uksb-1q9p31idr) (tag:parameters).

Parameters:
  S3BucketNamePrefix:
   Description: The prefix to use for your S3 bucket
   Type: String
   Default: cfn-workshop
   AllowedPattern: ^(?!(^xn--|.$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
   ConstraintDescription: Bucket name prefix can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).

Resources:
  DemoBucket:
   Type: AWS::S3::Bucket
   Properties:w
    BucketName: !Sub '${S3BucketNamePrefix}-${AWS::Region}-${AWS::AccountId}'